export const USER_SET_EMAIL = 'USER_SET_EMAIL',
USER_SET_PASSWORD = 'USER_SET_PASSWORD',
USER_SET_NAME = 'USER_SET_NAME',

USER_RESET_FORM = 'USER_RESET_FORM',
USER_PROFILE_DATA = 'USER_PROFILE_DATA',

SET_LOADING = 'SET_LOADING'